ASI Imaging XY Stage:
  X Limits: !!python/tuple
  - -5
  - 5
  Y Limits: !!python/tuple
  - -5
  - 5
Serial:
  baudrate: 115200
  bytesize: 8
  default_timeout: 0.1
  id_command: ""
  id_response: ""
  parity: N
  port: ttyUSB0
  rtscts: false
  stopbits: 1
  terminator: "\r"
  xonxoff: false
